# Generated by Django 5.2.6 on 2025-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=3, max_digits=5)),
                ('img_url', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
