# Generated by Django 5.2.6 on 2025-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0002_alter_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='Example_slug', unique=True),
            preserve_default=False,
        ),
    ]
