# Generated by Django 5.2.6 on 2025-10-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0010_alter_category_wastage_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='labour_cost',
        ),
        migrations.RemoveField(
            model_name='category',
            name='wastage_percent',
        ),
    ]
