# Generated by Django 5.2.6 on 2025-10-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0011_remove_category_labour_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
