# Generated by Django 5.2.6 on 2025-10-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0012_category_labour_cost_category_wastage_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
