# Generated by Django 5.2.6 on 2025-10-13 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0013_alter_category_wastage_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
