# Generated by Django 5.2.6 on 2025-10-14 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0014_goldrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='labour_cost',
        ),
        migrations.RemoveField(
            model_name='category',
            name='wastage_percent',
        ),
    ]
