# Generated by Django 5.2.6 on 2025-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0015_remove_category_labour_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='category',
            name='wastage_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
    ]
