# Generated by Django 5.2.6 on 2025-10-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSJ', '0016_category_making_charges_category_wastage_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_zip',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_on_card',
        ),
    ]
